### ISSUE TITLE
unable to install EdkRepo

### ISSUE THREAD

**Issue by KaymannWoo** [tianocore/edk2-edkrepo#127]
Getting the following error during install:

Found Python 3.11.1
Git Version: 2.27.0
Running git lfs install
Searching for existing EdkRepo installations...
Determining currently installed Python packages...
Uninstalling current version of edkrepo
Version 4.0.0 of package smmap is already installed
Version 4.0.7 of package gitdb is already installed
Version 3.1.14 of package GitPython is already installed
Version 0.4.4 of package colorama is already installed
Installing edkrepo version 3.1.0
Windows directory is in %PATH%.
Creating edkrepo launcher in Git Bash...
Creating python launcher in Git Bash...
Creating python3 launcher in Git Bash...
Installing EdkRepo command completion...
Copied win_edkrepo_prompt.sh
C:\windows\edkrepo.exe
C:\Program Files\Git\etc\profile.d\edkrepo_completions.sh
Traceback (most recent call last):
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_entry_point.py", line 94, in main
return(func())
^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_cli.py", line 161, in main
command = command_factory.create_composite_command()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 85, in create_composite_command
commands = get_commands()
^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 73, in get_commands
if in_same_module and _is_command(cls[1]):
^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 32, in _is_command
if func[0] == 'get_metadata' and len(inspect.getargspec(func[1])[0]) == 1:
^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
Traceback (most recent call last):
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_entry_point.py", line 94, in main
return(func())
^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_cli.py", line 161, in main
command = command_factory.create_composite_command()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 85, in create_composite_command

**Comment by ashedesimone** [comment]
Fixed in https://github.com/tianocore/edk2-edkrepo/pull/121

A new release with this fix will be posted shortly.

**Comment by ashedesimone** [comment]
Released as part of v3.1.1
