### ISSUE TITLE
[Customer Find] EDK Repo Setup Install Fails on Windows with Python 3.11.1

### ISSUE THREAD

**Issue by nnikolov-intel** [tianocore/edk2-edkrepo#169]
Found Python 3.11.1 
Git Version: 2.39.1
Running git lfs install
Searching for existing EdkRepo installations...
Determining currently installed Python packages...
Uninstalling current version of edkrepo
Version 4.0.0 of package smmap is already installed
Version 4.0.7 of package gitdb is already installed
Version 3.1.14 of package GitPython is already installed
Version 0.4.4 of package colorama is already installed
Installing edkrepo version 3.1.0
Windows directory is in %PATH%.
Creating edkrepo launcher in Git Bash...
Creating python launcher in Git Bash...
Creating python3 launcher in Git Bash...
Installing EdkRepo command completion...
Copied win_edkrepo_prompt.sh
C:\windows\edkrepo.exe
C:\Program Files\Git\etc\profile.d\edkrepo_completions.sh
Traceback (most recent call last):
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_entry_point.py", line 94, in main
return(func())
^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_cli.py", line 161, in main
command = command_factory.create_composite_command()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 85, in create_composite_command
commands = get_commands()
^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 73, in get_commands
if in_same_module and _is_command(cls[1]):
^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 32, in _is_command
if func[0] == 'get_metadata' and len(inspect.getargspec(func[1])[0]) == 1:
^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'
Traceback (most recent call last):
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_entry_point.py", line 94, in main
return(func())
^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_cli.py", line 161, in main
command = command_factory.create_composite_command()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 85, in create_composite_command
commands = get_commands()
^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 73, in get_commands
if in_same_module and _is_command(cls[1]):
^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 32, in _is_command
if func[0] == 'get_metadata' and len(inspect.getargspec(func[1])[0]) == 1:
^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "C:\windows\edkrepo.exe\__main__.py", line 7, in <module>
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_entry_point.py", line 99, in main
return edkrepo.edkrepo_cli.main()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\edkrepo_cli.py", line 161, in main
command = command_factory.create_composite_command()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 85, in create_composite_command
commands = get_commands()
^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 73, in get_commands
if in_same_module and _is_command(cls[1]):
^^^^^^^^^^^^^^^^^^^
File "C:\Users\klwoo\AppData\Local\Programs\Python\Python311\Lib\site-packages\edkrepo\commands\command_factory.py", line 32, in _is_command
if func[0] == 'get_metadata' and len(inspect.getargspec(func[1])[0]) == 1:
^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
Unable to launch preferred entry point. Launching default entry point edkrepo.edkrepo_cli.py
Installation Error:
System.InvalidOperationException: generate-command-completion-script failed with status 1
at TianoCore.EdkRepoInstaller.InstallWorker.PerformInstall(Action`2 ReportComplete, Action`1 ReportProgress, Action`1 AllowCancel, Func`1 CancelPending)
at TianoCore.EdkRepoInstaller.ProgressWindow.WorkerThread()
Installation Failed.

**Comment by nnikolov-intel** [comment]
Closing it because the issue was on EDKRepo 3.1.0 and EDKRepo 3.1.1 added support for Python 3.11
